apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-v1
data:
  nginx.conf: |-
    events {}
    http {
        server {
            listen 80;
            location / {
                return 200 '{"name":"backend","version":"1"}';
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: "1"
  template:
    metadata:
      labels:
        app: backend
        version: "1"
      annotations:
    spec:
      containers:
        - name: backend-v1
          image: "nginx"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: backend-v1
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: backend