apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-v2
data:
  nginx.conf: |-
    events {}
    http {
        server {
            listen 80;
            location / {
                return 200 '{"name":"backend","version":"2"}';
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: "2"
  template:
    metadata:
      labels:
        app: backend
        version: "2"
      annotations:
    spec:
      containers:
        - name: backend-v2
          image: "nginx"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: backend-v2